### ISSUE TITLE
Arrow entity renderer is broken

### ISSUE THREAD

**Issue by icehorse2401** [daWinzig/entity-separator#1]
Viewing arrow entities stuck in the player causes the game to crash because of this mod. This mod can easily be reproduced by getting a pillager to shoot oneself, then either going to third person view or viewing the inventory. Here's the log file:
	at MC/net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1346) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:636) ~[iris-1.7.0+mc1.20.5.jar:?]
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:505) ~[iris-1.7.0+mc1.20.5.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010) ~[iris-1.7.0+mc1.20.5.jar:?]
	at MC/net.minecraft.client.render.WorldRenderer.handler$blb000$iris$renderTerrainShadows(WorldRenderer.java:6802) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1009) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1093) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.GameRenderer.render(GameRenderer.java:858) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1320) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
Caused by: java.lang.IllegalStateException: Cannot encode empty ItemStack
	at MC/net.minecraft.item.ItemStack.encode(ItemStack.java:393) ~[client-intermediary.jar:?]
	at MC/net.minecraft.entity.projectile.PersistentProjectileEntity.writeCustomDataToNbt(PersistentProjectileEntity.java:513) ~[client-intermediary.jar:?]
	at MC/net.minecraft.entity.Entity.writeNbt(Entity.java:1860) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.EntityRenderer.handler$zmk000$entityseparator$render(EntityRenderer.java:1036) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.EntityRenderer.render(EntityRenderer.java) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.ProjectileEntityRenderer.render(ProjectileEntityRenderer.java:70) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.ProjectileEntityRenderer.render(ProjectileEntityRenderer.java:12) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:143) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.feature.StuckArrowsFeatureRenderer.renderObject(StuckArrowsFeatureRenderer.java:36) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.feature.StuckObjectsFeatureRenderer.render(StuckObjectsFeatureRenderer.java:47) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.feature.StuckObjectsFeatureRenderer.render(StuckObjectsFeatureRenderer.java:13) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer.java:149) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:68) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:45) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:143) ~[client-intermediary.jar:?]

**Comment by daWinzig** [comment]
Should be fixed with version [0.2.3](https://github.com/daWinzig/entity-separator/releases/tag/v0.2.3%2B1.20.5). Turns out Minecraft really doesn't like getting the NBT data of an arrow with an empty pickupItemStack.
Thank you for reporting it!
